# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v3 or later

name: Run the test suite

on:
- pull_request
- push

jobs:
  run-tests:
    name: Run the test suite
    strategy:
      matrix:
        python-version: [3.8, 3.12]  # no particular need for in-between versions
        runs-on: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run the test suite
      run: |
        set -x
        python3 --version
        pip3 install -U setuptools  # for Python >=3.12
        python3 setup.py test
