# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v3 or later

name: Run the test suite

on:
- pull_request
- push

jobs:
  run-tests:
    name: Run the test suite
    strategy:
      matrix:
        python-version: [3.8, 3.11]  # no particular need for in-between versions
        runs-on: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # v4.7.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run the test suite
      run: |
        set -e
        python --version
        python setup.py test
